steps:
  - name: build
    image: nixos/nix:latest
    volumes:
      - /opt/woodpeckerci/dind-certs:/opt/woodpeckerci/dind-certs
    environment:
      NIX_CONFIG: "experimental-features = nix-command flakes"
      TZ: "UTC"
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /opt/woodpeckerci/dind-certs/client
    commands:
      - nix build .#docker-image
    when:
      - event: push

  - name: load-image
    image: docker:cli
    volumes:
      - /opt/woodpeckerci/dind-certs:/opt/woodpeckerci/dind-certs
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /opt/woodpeckerci/dind-certs/client
    commands:
      - docker load < result
    depends_on:
      - build

  - name: test
    image: finances-web:latest
    environment:
      TZ: "UTC"
      RAILS_ENV: test
      DATABASE_URL: postgres://admin:adminpass@postgres:5432/finances_web_test
    commands:
      - bundle exec rake assets:precompile
      - bundle exec rake db:create db:migrate
      - bundle exec rspec
    depends_on:
      - build
    when:
      - event: push

  - name: push
    image: docker:24-cli
    volumes:
      - /opt/woodpeckerci/dind-certs:/opt/woodpeckerci/dind-certs
    environment:
      TZ: "UTC"
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /opt/woodpeckerci/dind-certs/client
    commands:
      - docker tag finances-web:latest nixserver:5000/finances-web:latest
      - docker push nixserver:5000/finances-web:latest
    depends_on:
      - build
      - test
    when:
      - event: push
        branch: main

services:
  - name: docker
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /opt/woodpeckerci/dind-certs
    volumes:
      - /opt/woodpeckerci/dind-certs:/opt/woodpeckerci/dind-certs

  - name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: finances_web_test
