steps:
  - name: build
    image: nixos/nix:latest
    volumes:
      - /opt/woodpeckerci/dind-certs:/opt/woodpeckerci/dind-certs
    environment:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
      TZ: "UTC"
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /opt/woodpeckerci/dind-certs/client
    commands:
      - nix build .#docker-image
      - cp result image.tar
    when:
      - event: push

  - name: test
    image: nixos/nix:latest
    environment:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
      TZ: "UTC"
      RAILS_ENV: test
      DATABASE_URL: postgres://admin:adminpass@postgres:5432/finances_web_test
    commands:
      - nix develop -c bundle exec rake assets:precompile RAILS_ENV=test
      - nix develop -c bundle exec rake db:create db:migrate RAILS_ENV=test
      - nix develop -c bundle exec rspec
    when:
      - event: push

  - name: push
    image: docker:24-cli
    volumes:
      - /opt/woodpeckerci/dind-certs:/opt/woodpeckerci/dind-certs
    environment:
      TZ: "UTC"
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /opt/woodpeckerci/dind-certs/client
    commands:
      - docker load --input image.tar
      - docker tag finances-web:latest nixserver:5000/finances-web:${CI_COMMIT_SHA:0:8}
      - docker push nixserver:5000/finances-web:${CI_COMMIT_SHA:0:8}
      - docker tag nixserver:5000/finances-web:${CI_COMMIT_SHA:0:8} nixserver:5000/finances-web:latest
      - docker push nixserver:5000/finances-web:latest
    depends_on:
      - test
    when:
      - event: push
        branch: main

  - name: deploy
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SENTRY_DSN:
        from_secret: SENTRY_DSN
    commands:
      - docker compose pull web
      - docker compose up -d web
    depends_on:
      - push
    when:
      - event: push
        branch: main

services:
  - name: docker
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /opt/woodpeckerci/dind-certs
    volumes:
      - /opt/woodpeckerci/dind-certs:/opt/woodpeckerci/dind-certs
      - /etc/nixos/daemon.json:/etc/docker/daemon.json

  - name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: finances_web_test


